######################################################################
# Automatically generated by qmake (3.0) Mon Mar 2 17:22:31 2015
######################################################################

TEMPLATE = app
TARGET = 81_GraphicView
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
